export const ROADMAP_IDEAS = [
  {
    id: "owasp-zap",
    title: "OWASP ZAP integration",
    category: "Integration",
    complexity: "High",
    effort: "2–3 weeks",
    stack: "ZAP API · Docker · async job queue",
    summary: "Deep active scanning with spider, fuzzer, and authenticated sessions via ZAP.",
    includes: ["Spider + active scan", "Auth session config", "ZAP report import"],
  },
  {
    id: "nuclei-community",
    title: "Full Nuclei template corpus",
    category: "Integration",
    complexity: "Medium",
    effort: "1 week",
    stack: "Nuclei CLI · template sync · CVE tagging",
    summary: "Sync thousands of community templates (bundled YAML + optional CLI today).",
    includes: ["Template sync", "CVE tagging", "Community coverage"],
  },
  {
    id: "compliance",
    title: "Compliance mapping",
    category: "Reporting",
    complexity: "Medium",
    effort: "1 week",
    stack: "OWASP ASVS · PCI DSS mapping · PDF export",
    summary: "Map findings to OWASP Top 10 and compliance frameworks.",
    includes: ["Framework tags", "Executive summary", "PDF export"],
  },
  {
    id: "dom-xss",
    title: "DOM XSS browser testing",
    category: "Scanning",
    complexity: "High",
    effort: "2–3 weeks",
    stack: "Playwright · DOM sinks · payload library",
    summary: "Browser-based DOM XSS detection beyond reflection checks.",
    includes: ["Sink tracing", "Payload library", "Evidence screenshots"],
  },
  {
    id: "team-workspaces",
    title: "Team workspaces",
    category: "Platform",
    complexity: "High",
    effort: "3+ weeks",
    stack: "Auth · RBAC · shared triage",
    summary: "Multi-user targets, roles, and shared finding workflows.",
    includes: ["User accounts", "Shared targets", "Audit log"],
  },
];
