/** Curated paths commonly tested by Nikto, OWASP ZAP, and Nuclei templates */
export const NIKTO_PATHS = [
  { path: "/.htaccess", severity: "high", title: ".htaccess file exposed", marker: /RewriteEngine|Deny from|Allow from/i },
  { path: "/.htpasswd", severity: "critical", title: ".htpasswd file exposed", marker: /:\$[a-z0-9./]+|\$apr1\$/i },
  { path: "/.user.ini", severity: "high", title: "PHP .user.ini exposed", marker: /(auto_prepend_file|open_basedir)\s*=/i },
  { path: "/composer.json", severity: "medium", title: "Composer manifest exposed", marker: /"require"\s*:/i },
  { path: "/composer.lock", severity: "medium", title: "Composer lockfile exposed", marker: /"packages"\s*:/i },
  { path: "/package.json", severity: "low", title: "package.json exposed", marker: /"name"\s*:\s*"/i },
  { path: "/package-lock.json", severity: "low", title: "package-lock.json exposed", marker: /"lockfileVersion"/i },
  { path: "/yarn.lock", severity: "low", title: "yarn.lock exposed", marker: /# yarn lockfile/i },
  { path: "/Gemfile", severity: "medium", title: "Ruby Gemfile exposed", marker: /source\s+['"]https:\/\/rubygems/i },
  { path: "/id_rsa", severity: "critical", title: "SSH private key exposed", marker: /BEGIN (?:RSA |OPENSSH )?PRIVATE KEY/i },
  { path: "/id_dsa", severity: "critical", title: "SSH private key exposed", marker: /BEGIN.*PRIVATE KEY/i },
  { path: "/.ssh/id_rsa", severity: "critical", title: "SSH private key in .ssh", marker: /BEGIN.*PRIVATE KEY/i },
  { path: "/.bash_history", severity: "high", title: "Shell history exposed", marker: /(sudo |ssh |mysql |curl )/i },
  { path: "/.mysql_history", severity: "high", title: "MySQL history exposed", marker: /(SELECT|INSERT|UPDATE|DELETE)\s/i },
  { path: "/elmah.axd", severity: "high", title: "ASP.NET ELMAH log exposed", marker: /Error Log for|ELMAH/i },
  { path: "/trace.axd", severity: "high", title: "ASP.NET trace exposed", marker: /Application Trace|trace.axd/i },
  { path: "/web.config.bak", severity: "critical", title: "IIS web.config backup", marker: /<configuration/i },
  { path: "/WEB-INF/web.xml", severity: "high", title: "Java WEB-INF/web.xml exposed", marker: /<web-app/i },
  { path: "/META-INF/MANIFEST.MF", severity: "medium", title: "Java MANIFEST exposed", marker: /Manifest-Version/i },
  { path: "/console", severity: "high", title: "Web console exposed", marker: /WebLogic|console|admin/i },
  { path: "/manager/html", severity: "critical", title: "Tomcat manager exposed", marker: /Tomcat Manager|manager-app/i },
  { path: "/host-manager/html", severity: "critical", title: "Tomcat host-manager exposed", marker: /Tomcat Host Manager/i },
  { path: "/jmx-console", severity: "critical", title: "JBoss JMX console exposed", marker: /JBoss|jmx-console/i },
  { path: "/invoker/JMXInvokerServlet", severity: "critical", title: "JBoss invoker servlet exposed", marker: /JBoss|JMX/i },
  { path: "/solr/admin", severity: "high", title: "Apache Solr admin exposed", marker: /Solr Admin|solr/i },
  { path: "/jenkins/login", severity: "high", title: "Jenkins login exposed", marker: /Jenkins/i },
  { path: "/hudson/login", severity: "high", title: "Hudson CI login exposed", marker: /Hudson/i },
  { path: "/_cat/indices", severity: "high", title: "Elasticsearch cat API exposed", marker: /"pri"\s*:\s*"|"rep"\s*:\s*"/i },
  { path: "/_all/_search", severity: "high", title: "Elasticsearch search API exposed", marker: /"took"\s*:\s*\d|"hits"\s*:\s*\{/i },
  { path: "/Dockerfile", severity: "medium", title: "Dockerfile exposed", marker: /^FROM /m },
  { path: "/docker-compose.yml", severity: "high", title: "Docker Compose file exposed", marker: /services:|version:/i },
  { path: "/kubernetes.yml", severity: "high", title: "Kubernetes manifest exposed", marker: /apiVersion:|kind:/i },
  { path: "/.kube/config", severity: "critical", title: "Kubernetes kubeconfig exposed", marker: /clusters:|users:/i },
  { path: "/server-status?auto", severity: "medium", title: "Apache server-status (auto)", marker: /ServerVersion|Total Accesses/i },
  { path: "/nginx_status", severity: "medium", title: "Nginx stub status exposed", marker: /Active connections|Reading:/i },
  { path: "/status.php", severity: "medium", title: "PHP status page", marker: /phpinfo\(\)|PHP Version/i },
  { path: "/test.php", severity: "medium", title: "PHP test script", marker: /phpinfo\(\)|PHP Version/i },
  { path: "/phpmyadmin/index.php", severity: "high", title: "phpMyAdmin login", marker: /phpMyAdmin/i },
  { path: "/adminer.php", severity: "high", title: "Adminer DB tool exposed", marker: /Adminer/i },
  { path: "/readme.html", severity: "low", title: "WordPress readme exposed", marker: /WordPress|Version/i },
  { path: "/license.txt", severity: "info", title: "WordPress license exposed", marker: /WordPress|GNU GENERAL PUBLIC LICENSE/i },
  { path: "/CHANGELOG.txt", severity: "low", title: "Changelog exposed", marker: /^#+\s|^\d+\.\d+\.\d+/m },
  { path: "/INSTALL.txt", severity: "low", title: "Install instructions exposed", marker: /install/i },
  { path: "/.npmrc", severity: "high", title: "npm config exposed", marker: /registry=|authToken/i },
  { path: "/.docker/config.json", severity: "critical", title: "Docker config exposed", marker: /"auths"|"credHelpers"/i },
  { path: "/api/swagger-ui.html", severity: "medium", title: "Swagger UI (Spring)", marker: /swagger|openapi/i },
  { path: "/api/v2/swagger.json", severity: "high", title: "Swagger JSON exposed", marker: /"swagger"|"openapi"/i },
  { path: "/.well-known/assetlinks.json", severity: "info", title: "Android asset links published", expectFound: true, marker: /"relation"/i },
  { path: "/.well-known/apple-app-site-association", severity: "info", title: "Apple app site association", expectFound: true, marker: /"applinks"/i },
  { path: "/clientaccesspolicy.xml", severity: "low", title: "Silverlight client access policy", marker: /access-policy|domain/i },
  { path: "/crossdomain.xml", severity: "low", title: "Flash crossdomain policy", marker: /cross-domain-policy|allow-access-from/i },
  { path: "/sftp-config.json", severity: "critical", title: "SFTP credentials config exposed", marker: /"(host|user|password)"\s*:/i },
  { path: "/.vscode/sftp.json", severity: "critical", title: "VS Code SFTP config exposed", marker: /"(host|username|password)"\s*:/i },
  { path: "/.idea/workspace.xml", severity: "medium", title: "JetBrains IDE workspace exposed", marker: /ProjectView|PropertiesComponent/i },
  { path: "/storage/logs/laravel.log", severity: "high", title: "Laravel log exposed", marker: /local\.ERROR|Stack trace/i },
  { path: "/logs/error.log", severity: "high", title: "Application error log exposed", marker: /(ERROR|FATAL|Exception)/i },
  { path: "/error.log", severity: "high", title: "Error log exposed", marker: /(ERROR|FATAL|Exception)/i },
  { path: "/access.log", severity: "medium", title: "Access log exposed", marker: /(GET |POST |HTTP\/)/i },
  { path: "/.hg/hgrc", severity: "high", title: "Mercurial repo config exposed", marker: /\[paths\]|\[ui\]/i },
  { path: "/CVS/Root", severity: "high", title: "CVS repository exposed", marker: /:ext:|:pserver:/i },
  { path: "/.bzr/README", severity: "high", title: "Bazaar repository exposed", marker: /Bazaar/i },
  { path: "/.gitignore", severity: "low", title: ".gitignore exposed", marker: /node_modules|\.env/i },
  { path: "/Procfile", severity: "info", title: "Heroku Procfile exposed", marker: /^web:/m },
  { path: "/appveyor.yml", severity: "info", title: "Appveyor CI config exposed", marker: /version:|build/i },
  { path: "/.travis.yml", severity: "info", title: "Travis CI config exposed", marker: /language:|script:/i },
  { path: "/circle.yml", severity: "info", title: "CircleCI config exposed", marker: /machine:|version:/i },
  { path: "/.github/workflows", severity: "info", title: "GitHub workflows path reachable", marker: /name:|on:/i },
];

export const BACKUP_SUFFIXES = [
  ".bak", ".backup", ".old", ".orig", ".save", ".swp", ".tmp", "~",
  ".copy", ".1", ".2", ".zip", ".tar.gz", ".sql",
];

export const DEFAULT_PAGE_SIGNATURES = [
  { path: "/", title: "Apache default page", marker: /Apache2 Ubuntu Default Page|It works!/i, server: /Apache/i },
  { path: "/", title: "Nginx welcome page", marker: /Welcome to nginx!/i, server: /nginx/i },
  { path: "/", title: "IIS default page", marker: /IIS Windows Server|Internet Information Services/i },
  { path: "/welcome", title: "Web server welcome page", marker: /Welcome to your new web server|Test Page for/i },
  { path: "/xampp", title: "XAMPP dashboard exposed", marker: /XAMPP|Bitnami/i },
  { path: "/phpmyadmin", title: "XAMPP phpMyAdmin default", marker: /phpMyAdmin/i },
];
