/** Nuclei-style JSON templates (method, path, matchers) */
export const BUILTIN_TEMPLATES = [
  { id: "tpl-git-head", name: "Git repository exposed", severity: "critical", method: "GET", path: "/.git/HEAD", matchers: [{ type: "word", words: ["ref: refs/"] }] },
  { id: "tpl-git-config", name: "Git config exposed", severity: "critical", method: "GET", path: "/.git/config", matchers: [{ type: "word", words: ["[core]"] }] },
  { id: "tpl-env", name: "Environment file exposed", severity: "critical", method: "GET", path: "/.env", matchers: [{ type: "regex", regex: ["^[A-Z][A-Z0-9_]*\\s*="] }] },
  { id: "tpl-spring-actuator", name: "Spring Boot actuator", severity: "high", method: "GET", path: "/actuator", matchers: [{ type: "word", words: ["_links", "/actuator/"] }] },
  { id: "tpl-spring-env", name: "Spring actuator env", severity: "critical", method: "GET", path: "/actuator/env", matchers: [{ type: "word", words: ["propertySources", "systemProperties"] }] },
  { id: "tpl-swagger-json", name: "Swagger JSON exposed", severity: "high", method: "GET", path: "/swagger.json", matchers: [{ type: "word", words: ['"swagger"', '"openapi"'] }] },
  { id: "tpl-openapi", name: "OpenAPI spec exposed", severity: "high", method: "GET", path: "/openapi.json", matchers: [{ type: "word", words: ['"openapi"'] }] },
  { id: "tpl-phpinfo", name: "PHPInfo page", severity: "high", method: "GET", path: "/phpinfo.php", matchers: [{ type: "word", words: ["phpinfo()", "PHP Version"] }] },
  { id: "tpl-tomcat-manager", name: "Tomcat manager", severity: "critical", method: "GET", path: "/manager/html", matchers: [{ type: "word", words: ["Tomcat Manager", "manager-app"] }] },
  { id: "tpl-jenkins", name: "Jenkins login", severity: "high", method: "GET", path: "/jenkins/login", matchers: [{ type: "word", words: ["Jenkins"] }] },
  { id: "tpl-elasticsearch", name: "Elasticsearch API", severity: "high", method: "GET", path: "/_cat/indices", matchers: [{ type: "word", words: ['"pri"', '"rep"'] }] },
  { id: "tpl-debug-php", name: "PHP debug bar", severity: "medium", method: "GET", path: "/_debugbar/open", matchers: [{ type: "word", words: ["debugbar", "phpdebugbar"] }] },
  { id: "tpl-wp-users", name: "WordPress user enum", severity: "medium", method: "GET", path: "/wp-json/wp/v2/users", matchers: [{ type: "word", words: ['"slug"', '"name"'] }] },
  { id: "tpl-docker-compose", name: "Docker compose file", severity: "high", method: "GET", path: "/docker-compose.yml", matchers: [{ type: "word", words: ["services:", "version:"] }] },
  { id: "tpl-kube-config", name: "Kubernetes kubeconfig", severity: "critical", method: "GET", path: "/.kube/config", matchers: [{ type: "word", words: ["clusters:", "users:"] }] },
  { id: "tpl-server-status", name: "Apache server-status", severity: "medium", method: "GET", path: "/server-status", matchers: [{ type: "word", words: ["Apache Server Status", "Server Version"] }] },
  { id: "tpl-nginx-status", name: "Nginx stub status", severity: "medium", method: "GET", path: "/nginx_status", matchers: [{ type: "word", words: ["Active connections", "Reading:"] }] },
  { id: "tpl-laravel-log", name: "Laravel log exposed", severity: "high", method: "GET", path: "/storage/logs/laravel.log", matchers: [{ type: "word", words: ["local.ERROR", "Stack trace"] }] },
  { id: "tpl-adminer", name: "Adminer exposed", severity: "high", method: "GET", path: "/adminer.php", matchers: [{ type: "word", words: ["Adminer", "pma_username"] }] },
  { id: "tpl-sftp-config", name: "SFTP config exposed", severity: "critical", method: "GET", path: "/sftp-config.json", matchers: [{ type: "word", words: ['"host"', '"password"'] }] },
  { id: "tpl-aws-creds", name: "AWS credentials file", severity: "critical", method: "GET", path: "/.aws/credentials", matchers: [{ type: "word", words: ["aws_access_key_id", "[default]"] }] },
  { id: "tpl-web-config", name: "web.config exposed", severity: "medium", method: "GET", path: "/web.config", matchers: [{ type: "word", words: ["<configuration"] }] },
  { id: "tpl-trace-axd", name: "ASP.NET trace", severity: "high", method: "GET", path: "/trace.axd", matchers: [{ type: "word", words: ["Application Trace", "trace.axd"] }] },
  { id: "tpl-metrics", name: "Prometheus metrics", severity: "high", method: "GET", path: "/metrics", matchers: [{ type: "regex", regex: ["^# HELP ", "^# TYPE "] }] },
];
